version: '3.9'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
       - "1883:1883"
       - "9001:9001"
    volumes:
      - /Users/javideveloper/work/mqtt-training/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /Users/javideveloper/work/mqtt-training/mosquitto/data:/mosquitto/data
      - /Users/javideveloper/work/mqtt-training/mosquitto/log:/mosquitto/log
    # security_opt:
      # - no-new-privileges:true
